config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'

  resources :homes
  resources :rooms

  patch '/chores/:id', to: 'chores#update', as: 'update_chore'
  get '/chores/dismiss_chore/:id', to: 'chores#dismiss_chore', as: 'dismiss_chore'
  get '/chores/meta/:id', to: 'chores#meta', as: 'chore_meta'
  resources :chores

  get '/chore_prerequisites/new', to: 'chore_prerequisites#new', as: 'new_prerequisite'
  post '/chore_prerequisites/new', to: 'chore_prerequisites#create', as: 'create_prerequisite'
  get '/chore_prerequisites/show', to: 'chore_prerequisites#show', as: 'chore_prerequisite'

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  belongs_to :room
  has_many :chore_prerequisites
  has_many :prerequisites, through: :chore_prerequisites

  validates :room_id, presence: true

  def days_overdue
    days_since_last_performed = (Date.today - last_performed).to_i
    days_since_last_performed > frequency ? (days_since_last_performed - frequency) : 0
  end

  def due?
    (Date.today - last_performed).to_i >= frequency
  end

  def effective_multiplier
    return 0 unless due?
    return multiplier ** ((Date.today - last_performed).truncate - frequency)
  end

  def effective_priority
    priority * effective_multiplier
  end
end

app/models/chore_prerequisite.rb
class ChorePrerequisite < ActiveRecord::Base
  belongs_to :chore
  belongs_to :prerequisite, class_name: "Chore"

  validates :prerequisite, uniqueness: { scope: :chore }
end

app/models/home.rb
class Home < ActiveRecord::Base
  has_many :rooms
  has_many :chores, through: :rooms

  def current_chores
    chores = []
    rooms.each do |r|
      r.current_chores.each do |c|
        chores << c
      end
    end
    chores
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :chores
  belongs_to :home

  def current_chores
    chores.select { |c| c.due? }.sort_by{ |c| -c.effective_priority }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chore_prerequisites_controller.rb
class ChorePrerequisitesController < ApplicationController
  def new
    @chore = Chore.find(params[:chore])
    @potential_prereqs = @chore.room.chores.select { |chore| chore != @chore }
  end

  def create
    @chore = Chore.find(prereq_params[:chore_id])
    @chore_prerequisite = nil
    prereq_ids = prereq_params[:prerequisite_ids]
    unless prereq_ids.nil?
      prereq_ids.each do |pr_id|
        @chore_prerequisite = ChorePrerequisite.create(chore_id: @chore.id, prerequisite_id: pr_id)
      end
    end
    redirect_to chore_meta_url(@chore)
  end

  private

  def prereq_params
    params.require(:chore_prerequisite).permit(:chore_id, prerequisite_ids: [])
  end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController

  def edit
    @chore = Chore.find(params[:id])
    @chore.update_attributes(last_performed: chore_params[:last_performed])
  end

  def update
    @chore = Chore.find(params[:id])
    @chore.update_attributes(chore_params)
    @chore.reload
    redirect_to action: "meta", id: @chore.id
  end

  def dismiss_chore
    @chore = Chore.find(params[:id])
  end

  def meta
    @chore = Chore.find(params[:id])
    @other_chores = @chore.room.chores.select { |c| c != @chore }.sort_by{ |c| -c.effective_priority }
  end

  private

  def chore_params
    params.require(:chore).permit(:frequency, :last_performed, :multiplier, :name, :priority, :room_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @homes = Home.all
  end

  def show
    @home = Home.find(params[:id])
    @chores = @home.current_chores.sort_by { |chore| -chore.effective_priority }
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @rooms = Room.all.each do |room|
      room.current_chores.sort_by! { |c| c.effective_priority }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/chore_prerequisites/create.html.erb
<%= render 'common/navbar' %>

app/views/chore_prerequisites/new.html.erb
<div class="prerequisites-form row">
  <h4 class="col-8 col-md-offset-2">Add prerequisite chores for: </h4>
  <h3 class="col-8 col-md-offset-2"><%= @chore.name %> (<%= @chore.room.name %>)</h3>
  <%= form_for :chore_prerequisite, html: { class: "new-prerequisites-form col-6 col-md-offset-3" } do |f| %>
    <%= f.hidden_field :chore_id, value: @chore.id %>
    <%= f.collection_check_boxes(:prerequisite_ids, @potential_prereqs, :id, :name, include_hidden: false) do |b| %>
      <div class="row">
        <%= b.label(class: "check_box col-12") do %>
          <div class="row">
            <div class="col-6">
              <%= b.object.name %>
            </div>

            <div class="col-1">
              <%= b.check_box(class: "check_box") %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= f.submit(class: "col-4 col-md-offset-4") %>
  <% end %>
</div>

app/views/chores/_chore_details.html.erb
<div id= "chore-tile-<%= chore.id %>" class="row chore-tile">
  <div class="col-6 ">
    <span><%= chore.name %></span>
  </div>
  <div class="col-2">
    <span><%= chore.last_performed.strftime("%_m/%_d/%Y") %></span>
  </div>
  <div class="col-3 btn-group" role="group">
    <%= link_to glyph(:ok), edit_chore_path(chore.id, chore: { last_performed: Date.today }), { remote:true, class: "btn btn-secondary btn-xs" } %>
    <%= link_to glyph(:remove), dismiss_chore_path(chore.id), { remote: true, class:"btn btn-secondary btn-xs" } %>
    <%= link_to glyph(:pencil), chore_meta_path(chore.id), class: 'btn btn-secondary btn-xs' %>
  </div>
</div>

app/views/chores/dismiss_chore.js.erb
$("#chore-tile-<%= @chore.id %>").closest('.chore-tile').remove();

app/views/chores/edit.js.erb
$("#chore-tile-<%= @chore.id %>").closest('.chore-tile').remove();

app/views/chores/meta.html.erb
<%= render 'common/navbar' %>
<div class="row">
  <div class="col-6">
    <div class="card col-9 col-md-offset-3">
      <%= form_for @chore do |f| %>
        <div class="row">
          <%= f.label :name, class: "col-4" %>
          <%= f.text_field :name, class: "long-text-field col-8" %><br />
        </div>
        <div class="row">
          <%= f.label :frequency, class: "col-4" %>
          <%= f.number_field :frequency, class: "col-8" %><br />
        </div>
        <div class="row">
          <%= f.label :last_performed, class: "col-4" %>
          <%= f.text_field :last_performed, class: "col-8" %><br />
        </div>
        <div class="row">
          <%= f.label :priority, class: "col-4" %>
          <%= f.number_field :priority, class: "col-8" %><br />
        </div>
        <div class="row">
          <%= f.label :room, class: "col-4" %>
          <%= f.select :room_id, Room.all.map { |r| [r.name, r.id] }, class: "col-8" %><br />
        </div>
        <div class="row">
          <%= f.label :multiplier, class: "col-4" %>
          <%= f.text_field :multiplier, class: "col-8" %><br />
        </div>
          <%= f.submit "Update Chore", class: "form-submit col-8 col-md-offset-4" %>
      <% end %>
    </div>
    <p class="col-5 col-md-offset-6">Prequisites:
      <% if @chore.prerequisites.empty? %>
        None </p>
      <% else %>
    </p>
        <ul class="col-5 col-md-offset-6 card">
          <% @chore.prerequisites.each do |p| %>
            <li class="prereq-list-item">
              <%= p.name %>
            </li>
          <% end %>
        </ul>
      <% end %>
    <%= link_to glyph(:plus), new_prerequisite_path(chore: @chore), class: 'btn btn-sm col-md-offset-6 col-1' %>
  </div>
  <div class="col-6 card">
    <ul><h4> Priority for other chores in <%= @chore.room.name %>:</h4>
      <% @other_chores.each do |other_chore| %>
        <li class="other-chore <%= 'undue' unless other_chore.due? %>">
          <%= link_to other_chore.name, chore_meta_path(other_chore), class: 'other-chore-link' %> - <%= other_chore.effective_priority.truncate %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/chores/show.html.erb
<%= render(file: 'chores/meta') %>

app/views/chores/update.html.erb
<%= render(file: 'chores/meta') %>

app/views/chores/update.js.erb
<% unless @chore.due? %>
  $("#chore-tile-<%= @chore.id %>").closest('.chore-tile').remove();
<% end %>

app/views/common/_header.html.erb
<h1><%= Home.first.name %></h1>

app/views/common/_navbar.html.erb
<div class="row">
  <div class="col-4"></div>
  <ul class="nav col-5 justify-content-md-center">
    <div class="row nav-links">
      <li class="nav-item col-6">
        <%= link_to "Show Rooms", room_path, class: 'nav-link' %>
      </li>
      <li class="nav-item col-6">
        <!-- TO-DO: Currently, home_path is hardcoded with id=1. When we add support for more homes, this must change. -->
        <%= link_to "All Current Chores", home_path(1), class: 'nav-link' %>
      </li>
    </div>
  </ul>
</div>

app/views/homes/_chore_tile.html.erb
<div id="chore-tile-<%= chore.id %>" class="chore-tile card">
    <div class="card-body col-12">
      <% unless chore.prerequisites.empty? %>
        <ul>
          <% chore.prerequisites.each do |p| %>
            <% if p.due? %>
              <div class="row">
                <li class="prereq-list-item col-12">
                  <span><%= link_to p.name, chore_meta_path(p), class: "chore-meta-link" %></span>
                  <div class="btn-group" role="group" aria-label="Basic example">
                    <%= link_to glyph(:ok), edit_chore_path(chore.id, chore: { last_performed: Date.today }), { remote:true, class: "btn btn-xs btn-secondary" } %>
                    <%= link_to glyph(:remove), dismiss_chore_path(chore.id), { remote: true, class:"btn btn-xs btn-secondary" } %>
                    <%= link_to glyph(:pencil), chore_meta_path(chore.id), class: 'btn btn-xs btn-secondary' %>
                  </div>

                </li>
              </div>
            <% end %>
          <% end %>
        </ul>
      <% end %>
      <h4 class="card-title"> <%= link_to chore.name, chore_meta_path(chore), class: 'chore-meta-link' %> (<%= chore.room.name %>)</h4>
      <p class="card-text">
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to glyph(:ok), edit_chore_path(chore.id, chore: { last_performed: Date.today }), { remote:true, class: "btn btn-secondary" } %>
          <%= link_to glyph(:remove), dismiss_chore_path(chore.id), { remote: true, class:"btn btn-secondary" } %>
          <%= link_to glyph(:pencil), chore_meta_path(chore.id), class: 'btn btn-secondary' %>
        </div>
      </p>
    </div>
</div>

app/views/homes/index.html.erb
<h1>Choose your location:</h1>

<% @homes.each do |h| %>
  <%= link_to h.name, home_path(h) %>
<% end %>

app/views/homes/show.html.erb
<%= render 'common/navbar' %>
<div class="row">
  <% @chores.each do |chore| %>
        <div class="chore-tile container col-4" >
          <%= render "chore_tile", chore: chore %>
        </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<head>
  <title>WhatsNext</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="content container">
    <%= render 'common/header' %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </div>
</body>
</html>

app/views/rooms/_room_chore_list_tile.html.erb
<% room.current_chores.each do |chore| %>
  <%= render 'chores/chore_details', chore: chore %>
<% end %>

app/views/rooms/show.html.erb
<%= render 'common/navbar' %>
  <div class="table-container container row">
    <table class="col-7 col-md-offset-2">
      <% @rooms.each do |room| %>
        <% if room.current_chores.count > 0 %>
          <tr class="row">
            <td class="col-1"><%= room.name %></td>
            <td class="col-11">
              <div class="room-chore-list-container" >
                <%= render "room_chore_list_tile", room: room %>
              </div>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
</div>